name: Build
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 2

      -
       name: Build and push 8.4 alpine
       uses: docker/build-push-action@v3
       with:
         file: "./src/docker/Dockerfile.alpine"
         push: true
         platforms: linux/amd64,linux/arm64
         build-args: |
           phpVersion=8.4
         tags: |
          "ghcr.io/ffreville/laravel-php-fpm:8.4-alpine"
      -
        name: Build and push 8.4
        uses: docker/build-push-action@v3
        with:
          file: "./src/docker/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=8.4
          tags: |
           "ghcr.io/ffreville/laravel-php-fpm:8.4"
           "ghcr.io/ffreville/laravel-php-fpm:latest"

